In [1]:
#INSTALL NECESSARY LIBRARIES
import numpy as np
import matplotlib as plt
import seaborn as sns
import pandas as pd

In [27]:
#IMPORT DATASET 

data = pd.read_csv(r"C:\Users\anjal\Downloads\SampleSuperstore.csv\SampleSuperstore.csv")

#r used for while importing csv just to adjust ["/" with "\"]

print(data)

           Ship Mode    Segment        Country             City       State  \
0       Second Class   Consumer  United States        Henderson    Kentucky
1       Second Class   Consumer  United States        Henderson    Kentucky
2       Second Class  Corporate  United States      Los Angeles  California
3     Standard Class   Consumer  United States  Fort Lauderdale     Florida
4     Standard Class   Consumer  United States  Fort Lauderdale     Florida
...              ...        ...            ...              ...         ...
9989    Second Class   Consumer  United States            Miami     Florida
9990  Standard Class   Consumer  United States       Costa Mesa  California
9991  Standard Class   Consumer  United States       Costa Mesa  California
9992  Standard Class   Consumer  United States       Costa Mesa  California
9993    Second Class   Consumer  United States      Westminster  California

      Postal Code Region         Category Sub-Category     Sales  Quantity  \
0         42420.0  South        Furniture    Bookcases  261.9600       2.0
1         42420.0  South        Furniture       Chairs  731.9400       3.0
2         90036.0   West  Office Supplies       Labels   14.6200       2.0
3         33311.0  South        Furniture       Tables  957.5775       5.0
4         33311.0  South  Office Supplies      Storage   22.3680       2.0
...           ...    ...              ...          ...       ...       ...
9989      33180.0  South        Furniture  Furnishings   25.2480       3.0
9990      92627.0   West        Furniture  Furnishings   91.9600       2.0
9991      92627.0   West       Technology       Phones  258.5760       2.0
9992      92627.0   West  Office Supplies        Paper   29.6000       4.0
9993      92683.0   West  Office Supplies   Appliances  243.1600       2.0

      Discount    Profit
0         0.00   41.9136
1         0.00  219.5820
2         0.00    6.8714
3         0.45 -383.0310
4         0.20    2.5164
...        ...       ...
9989      0.20    4.1028
9990      0.00   15.6332
9991      0.20   19.3932
9992      0.00   13.3200
9993      0.00   72.9480

[9994 rows x 13 columns]

In [7]:
#HEAD AND TAIL 

#TOP 5 ROWS FROM THE DATASET
top = data.head()
print(top)

#BOTTOM 5 ROWS FROM THE DATASET
bottom = data.tail()
print(bottom)

           Ship Mode   Segment        Country         City       State  \
9989    Second Class  Consumer  United States        Miami     Florida
9990  Standard Class  Consumer  United States   Costa Mesa  California
9991  Standard Class  Consumer  United States   Costa Mesa  California
9992  Standard Class  Consumer  United States   Costa Mesa  California
9993    Second Class  Consumer  United States  Westminster  California

      Postal Code Region         Category Sub-Category    Sales  Quantity  \
9989        33180  South        Furniture  Furnishings   25.248         3
9990        92627   West        Furniture  Furnishings   91.960         2
9991        92627   West       Technology       Phones  258.576         2
9992        92627   West  Office Supplies        Paper   29.600         4
9993        92683   West  Office Supplies   Appliances  243.160         2

      Discount   Profit
9989       0.2   4.1028
9990       0.0  15.6332
9991       0.2  19.3932
9992       0.0  13.3200
9993       0.0  72.9480

In [14]:
#Display basic information about the dataset like datatype and null values
detail = data.info()

#Display statistical summary of the dataset like count , mean,std ,min,max etc.
describe = data.describe()
print(describe)

Ship Mode       5
Segment         5
Country         5
City            5
State           5
Postal Code     5
Region          5
Category        5
Sub-Category    5
Sales           5
Quantity        5
Discount        5
Profit          5
dtype: int64

In [46]:
# Check for missing values
null = data.isnull().sum()
print(null)

# REMOVE MISSING VALUES
data.dropna(inplace= True)     #inplace used to add the modification permanently
print(data)

#Alternatively, fill missing values with a specific value
#1. backfill and frontfill
bfill = data.bfill(inplace=True)
print(bfill)
ffill = data.ffill()
print(ffill)

#IN OTHER SAY HANDLE THE MISSING VALUE IS TO FILL IT BY THE MEAN AND MODE OF THE COLUMN IF COLUMN HAVE CATEGORYICALL DATA THAN USE MODE ELSE USE MEAN/AVG
mean = data['Profit'].mean()
print(mean)

#the mean of profit column is 28.6 which is aaverage of whole column now if you add this to all the missing row the sum of whole column is same 
#before handling missing value and after handling missing value.
fillna = data['Profit'].fillna(28.6,inplace = True)
print(fillna)

Ship Mode       1
Segment         1
Country         1
City            1
State           1
Postal Code     1
Region          1
Category        1
Sub-Category    7
Sales           6
Quantity        1
Discount        1
Profit          1
dtype: int64
           Ship Mode    Segment        Country             City       State  \
0       Second Class   Consumer  United States        Henderson    Kentucky
1       Second Class   Consumer  United States        Henderson    Kentucky
2       Second Class  Corporate  United States      Los Angeles  California
3     Standard Class   Consumer  United States  Fort Lauderdale     Florida
4     Standard Class   Consumer  United States  Fort Lauderdale     Florida
...              ...        ...            ...              ...         ...
9989    Second Class   Consumer  United States            Miami     Florida
9990  Standard Class   Consumer  United States       Costa Mesa  California
9991  Standard Class   Consumer  United States       Costa Mesa  California
9992  Standard Class   Consumer  United States       Costa Mesa  California
9993    Second Class   Consumer  United States      Westminster  California

      Postal Code Region         Category Sub-Category     Sales  Quantity  \
0         42420.0  South        Furniture    Bookcases  261.9600       2.0
1         42420.0  South        Furniture       Chairs  731.9400       3.0
2         90036.0   West  Office Supplies       Labels   14.6200       2.0
3         33311.0  South        Furniture       Tables  957.5775       5.0
4         33311.0  South  Office Supplies      Storage   22.3680       2.0
...           ...    ...              ...          ...       ...       ...
9989      33180.0  South        Furniture  Furnishings   25.2480       3.0
9990      92627.0   West        Furniture  Furnishings   91.9600       2.0
9991      92627.0   West       Technology       Phones  258.5760       2.0
9992      92627.0   West  Office Supplies        Paper   29.6000       4.0
9993      92683.0   West  Office Supplies   Appliances  243.1600       2.0

      Discount    Profit
0         0.00   41.9136
1         0.00  219.5820
2         0.00    6.8714
3         0.45 -383.0310
4         0.20    2.5164
...        ...       ...
9989      0.20    4.1028
9990      0.00   15.6332
9991      0.20   19.3932
9992      0.00   13.3200
9993      0.00   72.9480

[9961 rows x 13 columns]
None
           Ship Mode    Segment        Country             City       State  \
0       Second Class   Consumer  United States        Henderson    Kentucky
1       Second Class   Consumer  United States        Henderson    Kentucky
2       Second Class  Corporate  United States      Los Angeles  California
3     Standard Class   Consumer  United States  Fort Lauderdale     Florida
4     Standard Class   Consumer  United States  Fort Lauderdale     Florida
...              ...        ...            ...              ...         ...
9989    Second Class   Consumer  United States            Miami     Florida
9990  Standard Class   Consumer  United States       Costa Mesa  California
9991  Standard Class   Consumer  United States       Costa Mesa  California
9992  Standard Class   Consumer  United States       Costa Mesa  California
9993    Second Class   Consumer  United States      Westminster  California

      Postal Code Region         Category Sub-Category     Sales  Quantity  \
0         42420.0  South        Furniture    Bookcases  261.9600       2.0
1         42420.0  South        Furniture       Chairs  731.9400       3.0
2         90036.0   West  Office Supplies       Labels   14.6200       2.0
3         33311.0  South        Furniture       Tables  957.5775       5.0
4         33311.0  South  Office Supplies      Storage   22.3680       2.0
...           ...    ...              ...          ...       ...       ...
9989      33180.0  South        Furniture  Furnishings   25.2480       3.0
9990      92627.0   West        Furniture  Furnishings   91.9600       2.0
9991      92627.0   West       Technology       Phones  258.5760       2.0
9992      92627.0   West  Office Supplies        Paper   29.6000       4.0
9993      92683.0   West  Office Supplies   Appliances  243.1600       2.0

      Discount    Profit
0         0.00   41.9136
1         0.00  219.5820
2         0.00    6.8714
3         0.45 -383.0310
4         0.20    2.5164
...        ...       ...
9989      0.20    4.1028
9990      0.00   15.6332
9991      0.20   19.3932
9992      0.00   13.3200
9993      0.00   72.9480

[9961 rows x 13 columns]
28.557275725328783
None

C:\Users\anjal\AppData\Local\Temp\ipykernel_12596\2234199381.py:22: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  fillna = data['Profit'].fillna(28.6,inplace = True)

In [45]:
#check the duplicate rows
dup = data.duplicated().sum()
print(dup)

#drop duplicate rows
dropna = data.drop_duplicates(inplace = True)
print(dropna)

0
None

In [44]:
data.head(5)

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
0,Second Class,Consumer,United States,Henderson,Kentucky,42420.0,South,Furniture,Bookcases,261.9600,2.0,0.00,41.9136
1,Second Class,Consumer,United States,Henderson,Kentucky,42420.0,South,Furniture,Chairs,731.9400,3.0,0.00,219.5820
2,Second Class,Corporate,United States,Los Angeles,California,90036.0,West,Office Supplies,Labels,14.6200,2.0,0.00,6.8714
3,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,Furniture,Tables,957.5775,5.0,0.45,-383.0310
4,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,Office Supplies,Storage,22.3680,2.0,0.20,2.5164